### ISSUE TITLE
Double free possible?

### ISSUE THREAD

**Issue by chpio** [DaseinPhaos/aren_alloc#1]
[Pointer is clonable](https://github.com/DaseinPhaos/aren_alloc/blob/5fca9f02cb6e9aed777c350c287193e552c61f82/src/lib.rs#L134). You may end up with multiple pointers referencing the same space, resulting in double frees when dropped.

**Comment by DaseinPhaos** [comment]
It seems to be right, thanks!
Not sure why I added that line in the first place.
